### ISSUE TITLE
Transparency for telescope 

### ISSUE THREAD

**Issue by shouyierban** [scottmckendry/cyberdream.nvim#147]
### Description

**hi  scottmckendry, thank you for your job, and this is a very nice theme.**
this is a problem about Transparency. when I set `cache = true`,  the transparency of telescope and neotree become to invalid, even if I delete the old cache files。Hopefully you can fix it.

![image](https://github.com/user-attachments/assets/43ff2a46-81c2-4544-ae5a-b9ffc1077701)

### Neovim version?

v0.10

**Comment by scottmckendry** [comment]
hello @shouyierban :)
Can you share your config, I'm not able to replicate the above with my testing. 

You may need to run `:CyberdreamBuildCache` with cache disabled to get the desired result.

**Comment by shouyierban** [comment]
> 你好@shouyierban:) 您能分享您的配置吗？我无法通过我的测试复制上述内容。
> 
> 您可能需要`:CyberdreamBuildCache`在禁用缓存的情况下运行才能获得所需的结果。

thank you for your reply, here is my config:

`return {
    "scottmckendry/cyberdream.nvim",
    -- dev = true,
    lazy = false,
    priority = 1000,
    config = function()
      require("cyberdream").setup({
          transparent = true,
          italic_comments = true,
          hide_fillchars = true,
          terminal_colors = false,
          cache = true,
          borderless_telescope = false,
      })
  end,
}`
![image](https://github.com/user-attachments/assets/9a7e5c73-ee78-4b72-af66-f554736cfa36)

it works only I set ` cache = false`, but there was spend more time to start lazyvim

**Comment by scottmckendry** [comment]
Can you try setting `cache = false` so the correct highlights are shown? Once the highlights are showing correctly, run `:CyberdreamBuildCache`. 

This should fix the problem 🙂

**Comment by shouyierban** [comment]
> Can you try setting `cache = false` so the correct highlights are shown? Once the highlights are showing correctly, run `:CyberdreamBuildCache`.
> 
> This should fix the problem 🙂

I have tryed in this way, but still no work.
In lieu of that, after I manually modified the cache file and added the following, it displays properly.

```
{
  "TelescopeBorder": {
      "bg": "NONE"
  },
  "NeoTreeNormal": {
      "bg": "NONE"
  },
  "NeoTreeNormalNC": {
      "bg": "NONE"
  },
  "NeoTreeFileName": {
      "fg": "#ffffff"
  },
  "WhichKeyBorder": {
      "bg": "NONE"
  },
  "WhichKeyNormal": {
      "bg": "NONE"
  },
}
```

**Comment by Yeastiest** [comment]
Is there any way to make telescope completely transparent? When I'm not using any colourscheme and it defaults to my terminal scheme, telescope is transparent, but when using cyberdream and the config above, as well as setting telescope options like set_hl, it still isnt transparent.

**Comment by scottmckendry** [comment]
@Yeastiest try `borderless_telescope = false` in your config. Probably not the best setting name looking back 😀

**Comment by scottmckendry** [comment]
Hey @shouyierban, can you let me know if the latest commit on main resolves the original issue you reported? The `cache` option should now handle changes to the config after exiting Neovim the second time.

**Comment by shouyierban** [comment]
> Hey @shouyierban, can you let me know if the latest commit on main resolves the original issue you reported? The `cache` option should now handle changes to the config after exiting Neovim the second time.

Hi @scottmckendry , I have updated today. Unfortunately, it dose still not work like before, and I have checked cache file, some configuration iterms still needs to be added manually.
```
"NeoTreeNormal": {
      "bg": "NONE"
  },
  "NeoTreeNormalNC": {
      "bg": "NONE"
  },
  "NeoTreeFileName": {
      "fg": "#ffffff"
  },
  "WhichKeyBorder": {
      "bg": "NONE"
  },
  "WhichKeyNormal": {
      "bg": "NONE"
  }, 
  "TelescopeNormal": {
      "bg": "NONE"
  }
```

**Comment by scottmckendry** [comment]
Is it possible you're loading another colorscheme before cyberdream? The background colour `#1e2131` in your screenshot isn't defined anywhere in the code base, so it must be getting set by another plugin somehow. 

It has highlighted that both the whichkey and telescope extensions were missing some defaults, so those have been added now. 

I don't have an extension for neotree in cyberdream yet, but will look to add support soon. In the meantime, I'd recommend reviewing your config for any other plugins that could be setting these highlights 🙂

**Comment by shouyierban** [comment]
> Is it possible you're loading another colorscheme before cyberdream? The background colour `#1e2131` in your screenshot isn't defined anywhere in the code base, so it must be getting set by another plugin somehow.
> 
> It has highlighted that both the whichkey and telescope extensions were missing some defaults, so those have been added now.
> 
> I don't have an extension for neotree in cyberdream yet, but will look to add support soon. In the meantime, I'd recommend reviewing your config for any other plugins that could be setting these highlights 🙂

**Hi @scottmckendry , good news, it works now! thank you for your nice job, and Looking forward to neotree joining，there will be a perfect theme.**
By the way, is it possible to make the autocomplete window of blinkcmp to transparent? the documentation window is transparent now. I'm not sure if this is a theme issue or a plugin issue of blink-cmp.
![Quicker_20241126_105523](https://github.com/user-attachments/assets/e954c401-7d8e-4348-9ae7-77ef376549db)

**Comment by scottmckendry** [comment]
Great! glad to hear. And thank you for the kind words!

> is it possible to make the autocomplete window of blinkcmp to transparent?

Hmm, I don't have an answer to that one. blink.cmp is working fine in my case:

![image](https://github.com/user-attachments/assets/29420fdf-4cce-419b-a6ba-2e8835b05381)

Can you tell me what the output of `:hi BlinkCmpMenu` is? It should link to `Pmenu` which, in turn, should have a transparent background. Unless you have that group overridden somewhere else?

You could also try overriding `BlinkCmpMenu` in your config, like you did for the other groups to see if that makes any difference.

Btw I saw [your issue](https://github.com/Saghen/blink.cmp/issues/377) in blink.cmp - I don't think this is an issue with the plugin itself. I'm one of the contributors on that project and have been using it with cyberdream for ages with no problem.

**Comment by scottmckendry** [comment]
Actually, I can replicate this if I set `winblend = 1` in blink.cmp's setup:

![image](https://github.com/user-attachments/assets/8c630fda-1b1d-4e2d-ae18-abee50c91db7)

removing the `winblend` option entirely fixes this for me - maybe that is the problem?

**Comment by shouyierban** [comment]
> Actually, I can replicate this if I set `winblend = 1` in blink.cmp's setup:
> 
> ![image](https://private-user-images.githubusercontent.com/39483124/389833736-8c630fda-1b1d-4e2d-ae18-abee50c91db7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2ODE1MTQsIm5iZiI6MTczMjY4MTIxNCwicGF0aCI6Ii8zOTQ4MzEyNC8zODk4MzM3MzYtOGM2MzBmZGEtMWIxZC00ZTJkLWFlMTgtYWJlZTUwYzkxZGI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI3VDA0MjAxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU1YWFkZGM1YzNjMTE0ZmRmODI3ZjRlNDRkMzJkOThmYzY5NjBlMGNmZDE0N2VkMTU1MGFiYjYyMzg3NTA5ZDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.5bevsOoFgVHP8oGvP8NmMzXe1l6XxEN6Kd03C2IdTgA)
> 
> removing the `winblend` option entirely fixes this for me - maybe that is the problem?

The problem was solved, I added `winblend = 0` to the config file, and then it worked fine. Before this I had been using the default configuration and did not add `winblend = 0` to my config file.
Thanks again for your reply and suggestions.
