### ISSUE TITLE
UI bug for floating window

### ISSUE THREAD

**Issue by MaxHiit** [scottmckendry/cyberdream.nvim#179]
### Hi,

I have a color contrast problem when a floating window is open, especially the one concerning autocompletions, for example with cmp-nvim and wilder.nvim.

I get the impression that there's a background behind the word, symbol and gender selected.
Note also that the selection leaves the border and part of the border on the right does not exist.

![Image](https://github.com/user-attachments/assets/24334768-7d27-4323-8213-1f72fb373bce)

If you take the catppuccin theme, you'll notice that the selected background is continuous, so there's no difference.

![Image](https://github.com/user-attachments/assets/7b858ddd-b9e4-4305-a6c2-792de8e5fa26)

Does anyone have an idea for a change?

### Neovim version?
NVIM v0.11.0
Build type: Release
LuaJIT 2.1.1741730670

### What should happen?
No response

### What happened instead?
Comments should be italicized

### Your configuration
```lua
return {
    "scottmckendry/cyberdream.nvim",
    lazy = false,
    priority = 1000,
    config = function()
        require("cyberdream").setup({
	    variant = "auto",
	    transparent = false,
	    italic_comments = true,
	    hide_fillchars = true,
	    terminal_colors = false,
	    cache = true,
	    borderless_pickers = false,
	    extensions = {
	        dashboard = true,
		cmp = true,
		gitsigns = true,
		markdown = true,
		noice = true,
		notify = true,
		snacks = true;
		telescope = true,
		treesitter = true,
		treesittercontext = true,
		indentblankline = true,
		mini = true,
	    },
        })

        vim.cmd("colorscheme cyberdream")
    end,
}
```

**Comment by scottmckendry** [comment]
Not sure about wilder.nvim, but the commit I just pushed should fix the issue for nvim-cmp. Let me know if it looks okay after updating 🙂

**Comment by MaxHiit** [comment]
Nothing has changed after the update

**Comment by scottmckendry** [comment]
Can you please share your nvim-cmp config? I've now switched to Blink.cmp, but I was a long time user of nvim-cmp and never ran into this problem with cyberdream.

Does the issue still occur if you set `transparent = true` in your cyberdream.nvim config?

**Comment by MaxHiit** [comment]
I also changed to blink-cmp but it also has the problem. Yes the issue still here with `transparent = true` !

![Image](https://github.com/user-attachments/assets/f0e1d7f4-2589-4c3e-820b-82991415a3d7)

Here is the Blink config
```lua
return {
	"saghen/blink.cmp",
	-- use a release tag to download pre-built binaries
	version = "1.*",
	dependencies = { "rafamadriz/friendly-snippets" },
	--- @module 'blink.cmp'
	--- @type blink.cmp.Config
	opts = {
		keymap = {
			-- All presets have the following mappings:
			-- <tab>/<s-tab>: move to right/left of your snippet expansion
			-- <c-space>: Open menu or open docs if already open
			-- <c-n>/<c-p> or <up>/<down>: Select next/previous item
			-- <c-e>: Hide menu
			-- <c-k>: Toggle signature help
			--
			-- See :h blink-cmp-config-keymap for defining your own keymap
			preset = "default",
		},
		appearance = {
			nerd_font_variant = "mono",
		},
		completion = {
			menu = {
				border = "rounded",
			},
			documentation = {
				auto_show = true,
				auto_show_delay_ms = 500,
				window = {
					border = "rounded",
					desired_min_width = 30,
				},
			},
		},
		signature = { enabled = true },
		sources = {
			default = { "lsp", "path", "snippets", "buffer" },
		},
		fuzzy = { implementation = "prefer_rust_with_warning" },
	},
	opts_extend = { "sources.default" },
}
```

Cyberdream Config
```lua
return {
	"scottmckendry/cyberdream.nvim",
	lazy = false,
	priority = 1000,
	config = function()
		require("cyberdream").setup({
			variant = "auto",
			transparent = true,
			italic_comments = true,
			hide_fillchars = true,
			terminal_colors = false,
			cache = true,
			borderless_pickers = false,
			extensions = {
				dashboard = true,
				blinkcmp = true,
				gitsigns = true,
				markdown = true,
				noice = true,
				notify = true,
				fzflua = true,
				snacks = true,
				treesitter = true,
				treesittercontext = true,
				indentblankline = true,
				mini = true,
			},
		})

		vim.cmd("colorscheme cyberdream")
	end,
}
```

**Comment by scottmckendry** [comment]
Hey @MaxHiit 

I didn't mean for this issue to be closed, but it got picked up by the recent release. Sorry about that.

That being said, I'm having trouble tracking down what could be causing this. I'm not able to replicate the behaviour on my side of things. 

In your most recent screenshot, it looks like there are other issues with how the floating window is rendering. The border looks a bit odd, and the extra characters next to the icons also look a bit out of place.

I have a suspicion that your terminal or multiplexer could be causing some problems here, perhaps even the font. You mentioned that catpuccin was working fine, is this still the case?
